# Generated by Django 2.0.13 on 2019-05-14 10:31

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_item', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Inventaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kondisi', models.CharField(max_length=200)),
                ('keterangan', models.TextField()),
                ('jumlah', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('kode', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kode', models.CharField(max_length=10)),
                ('keterangan', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('nama_pegawai', models.CharField(max_length=200)),
                ('nip', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('alamat', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateTimeField(verbose_name='Tanggal Peminjaman')),
                ('tanggal_kembali', models.DateTimeField(blank=True, null=True)),
                ('status_peminjaman', models.CharField(choices=[('0', 'Dipinjam'), ('1', 'Dikembalikan')], max_length=1)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('inventaris', models.ManyToManyField(through='inventaris.Detail', to='inventaris.Inventaris')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.Pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kode', models.CharField(max_length=16)),
                ('keterangan', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='inventaris',
            name='jenis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.Jenis'),
        ),
        migrations.AddField(
            model_name='inventaris',
            name='ruang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.Ruang'),
        ),
        migrations.AddField(
            model_name='inventaris',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detail',
            name='inventaris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.Inventaris'),
        ),
        migrations.AddField(
            model_name='detail',
            name='peminjaman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.Peminjaman'),
        ),
    ]
